---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go CI/CD

on:
  push:
    tags: ["*"]

  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  pull_request:
    paths:
      - ".github/workflows/goreleaser.yaml"
      - "go.mod"
      - "go.sum"
      - "**/**.go"

jobs:
  lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@feat/go
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Run Tests
        run: mise run test

  goreleaser:
    needs: [lint, test]
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-release.yaml@feat/go
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
