---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go CI/CD

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        required: false
        default: false
        type: boolean

  # Dry Run on any PR that changes this pipeline or that should ultimately trigger a release when merged
  pull_request:
    paths:
      - ".github/workflows/goreleaser.yaml"
      - "go.mod"
      - "go.sum"
      - "**/**.go"

  # "Wet" Run on any tag push
  push:
    tags: ["*"]

jobs:
  lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@chore/cleanup
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    container: docker.io/library/golang:1.24.0-bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install minikube
        run: go install k8s.io/minikube/cmd/minikube@latest

      - name: Run Tests
        run: bash scripts/test.sh

  goreleaser:
    needs: [lint, test]
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-release.yaml@chore/cleanup
    secrets: inherit
    with:
      dry-run: ${{ inputs.dry-run || github.event_name == 'pull_request' }}
