---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    secrets: inherit
    with:
      # renovate: depName=go datasource=golang-version
      go-version: 1.24
      # renovate: depName=golangci/golangci-lint datasource=github-tags
      golangci-lint-version: v1.64.6

  actions:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    secrets: inherit
    with:
      config-file: .github/configs/actionlint.yaml

  commits:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    secrets: inherit
    with:
      config-file: ./.github/configs/commitlint.config.mjs

  markdown:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    secrets: inherit
    with:
      config-file: .github/configs/.markdownlint.yaml

  shell:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    secrets: inherit

  yaml:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamlfmt.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    secrets: inherit
    with:
      config-file: .github/configs/yamlfmt.yaml
