---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  # Manual Trigger
  workflow_dispatch: {}

  # Run on any PR
  pull_request: {}

jobs:
  golangci-lint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-go-lint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    secrets: inherit

  yamllint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamllint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    secrets: inherit
    with:
      yamllint-args: "--config-file=.yamllint.yaml"

  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    secrets: inherit

  shellcheck:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@a250168bca02c9de8d5bba45c0f5fa6d09892eed # v3.7.3
    secrets: inherit
