---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit
    with:
      config-file: .github/configs/actionlint.yaml

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit
    with:
      config-file: ./.github/configs/commitlint.config.mjs

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit
    with:
      config-file: .github/configs/.markdownlint.yaml

  shellcheck:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-shellcheck.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit

  yamllint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-yamllint.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit
    with:
      config-file: .github/configs/.yamllint.yaml
