---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  # Manual Trigger
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry Run
        default: false
        required: false
        type: boolean
      log-level:
        description: Log Level
        default: debug
        required: false
        type: string

  # "Wet" Run every 20 minutes
  schedule:
    - cron: "*/20 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-renovate.yaml@71c748260211464d1d58c43d7fb019f7adac19b3 # v3.5.1
    secrets: inherit
    with:
      dry-run: "${{ inputs.dry-run == true || github.event_name == 'pull_request' }}"
      log-level: "${{ inputs.log-level || 'debug' }}"
      config-file: .github/configs/renovate.json5
